# Generated by Django 5.0.6 on 2024-07-05 05:54

import items_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, validators=[items_api.validators.validate_no_numbers]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
