# Generated by Django 5.0.6 on 2024-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.SmallIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
