# Generated by Django 5.0.6 on 2024-07-08 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=200)),
                ('product_id', models.IntegerField(default=True)),
                ('quantity', models.IntegerField(default=True)),
                ('user_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cart_items_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
