# Generated by Django 5.0.6 on 2024-07-09 08:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countcart', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalbill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateField(default=datetime.date.today)),
                ('user_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
