# Generated by Django 5.0.6 on 2024-07-01 05:11

import django.db.models.deletion
import profiles_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(default=profiles_api.models.generate_id, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(default=profiles_api.models.generate_id, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('marital_status', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('medications', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('emg_contact_name', models.CharField(max_length=100)),
                ('emg_contact_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateField()),
                ('slot', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.patient')),
            ],
        ),
    ]
