# Generated by Django 5.0.6 on 2024-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.FloatField(max_length=255)),
            ],
        ),
    ]
