# Generated by Django 5.0.6 on 2024-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_alter_movie_release_date_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='movie_id',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.FloatField(max_length=255),
        ),
    ]
