# Generated by Django 5.0.6 on 2024-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.IntegerField(),
        ),
    ]
