# Generated by Django 5.0.6 on 2024-07-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0004_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='../../assets/images/default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.CharField(default='../../assets/images/default.jpg', max_length=255),
        ),
    ]
