# Generated by Django 5.0.6 on 2024-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_api', '0003_alter_userprofile_id_loanapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='tenure',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
