# Generated by Django 5.0.6 on 2024-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_api', '0004_alter_loanapplication_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='tenure',
            field=models.PositiveIntegerField(),
        ),
    ]
